### ISSUE TITLE
Anotation Transfer

### ISSUE THREAD

**Issue by victorgmlyra** [tarun738/i3DMM#3]
Hi, thank you for making your work open-source!

I want to know how to do the annotation transfer you mentioned in section 4.6 of your paper. I didn't see any mention of it in the code.

Thank you.

**Comment by tarun738** [comment]
Hi Victor,

Thanks for your interest in our work!

The code to do this is simple, we take our favorite KNN implementation and fit the points of the reference space of the target mesh which is represented using i3DMM.
`targetPC = densely sampled 3D points of target mesh
targetRef = points in reference space of i3DMM corresponding to targetPC
tree=knn.fit(targetRef)`

We take the source annotation points in the reference space and find the nearest neighbors in the target. The indices of the obtained nearest neighbors can be used to transfer annotations to the target 3D points.
`_,idx = tree(annotations of source mesh in reference space of i3DMM)
targetAnnotations = target3D[idx]`

Hope that helps!
Best,
Tarun
