### ISSUE TITLE
The results of training is bad

### ISSUE THREAD

**Issue by xusensun** [tarun738/i3DMM#4]
Hello, I follow you advice to prepare the data and train the model, but the result is bad. To make sure my data is correct, I train the model with one model in your test data, the result is bad too. Do you know the reason ? The following are my steps of training:

1. I set train_color=0, train_geometry=0, and train_reference=1, to train to refNet in 1001 Epoch
2. I set train_color=1, train_geometry=1, and train_reference=0, to train all networks in 5000 Epoch

The following are the fitting results

my own dataset
![00340_e30](https://user-images.githubusercontent.com/76764358/140056742-8f3d5344-aff8-4c07-a44e-563f0cfafba4.png)

your test dataset
![10101_e16](https://user-images.githubusercontent.com/76764358/140056800-a2bd8942-d7f6-41e2-ab30-95b46b706763.png)

Looking forward your apply!

**Comment by tarun738** [comment]
Hello,

Thank you for trying out our work!

We also do train the reference network in the second stage. So that shouldn't be 0.

Could you please tell me the number of meshes you are using to train the network?

**Comment by xusensun** [comment]
Thanks for your replying!

I will set train_reference=1 in the second stage.

We have 300 subjects. For each subject, we have 20 expressions. So, the total meshes is 300*20=6000.
To confirm the model is right, we use sereval meshes (less than 10) to train the model. We want to overfit it and test only on these model. If it is right, then we will train with all the meshes.

The bad results maybe duo to the number of meshes is less ? Or the number of epoch is less in both two stage?

**Comment by tarun738** [comment]
Please try training with one shape while also training the reference shape for sanity. (Also do check if the meshes are closed and preprocessing is happening well)

With just 10, the issue is that the network does not get enough information to deform for expressions and a wide range of hairstyles (if they vary widely in the data). We did not test it with 6000, our model was trained with ~600. So, that should already give similar results if the expression annotations are well.

**Comment by xusensun** [comment]
> Hello,
> 
> Thank you for trying out our work!
> 
> We also do train the reference network in the second stage. So that shouldn't be 0.
> 
> Could you please tell me the number of meshes you are using to train the network?

Thanks for replying!
I noticed that in line 500 ~ line 506 of train_i3DMM.py, if I set train_reference=1, the train_split_file will be overlap by ref_split_file, then the model will only train on the ref_split_file, not the train_split_file. So are you sure this parameter should be set 1 ?

Looking foward your replying!

**Comment by tarun738** [comment]
Sorry. Missed that part. train_geometry already trains the reference.

**Comment by xusensun** [comment]
> Please try training with one shape while also training the reference shape for sanity. (Also do check if the meshes are closed and preprocessing is happening well)
> 
> With just 10, the issue is that the network does not get enough information to deform for expressions and a wide range of hairstyles (if they vary widely in the data). We did not test it with 6000, our model was trained with ~600. So, that should already give similar results if the expression annotations are well.


Thanks you for replying !

I try training with one shape (10101_e16 in test your dataset) while also training the reference shape for sanity.  I think only train with this mesh, and the model will overfit it. Then I can fit this mesh well. Do you think so ?  Is there a preblem with this method ?

Or do you think I should train the model with a large dataset ? Maybe less dataset can train a good model ?

**Comment by tarun738** [comment]
Training with one should overfit the model well. However, you should run it for many more iterations e.g. 5k.

When you are training on a larger dataset, the given settings should work.

**Comment by xusensun** [comment]
> Training with one should overfit the model well. However, you should run it for many more iterations e.g. 5k.
> 
> When you are training on a larger dataset, the given settings should work.
> 
> Edit: Also when fitting to a few meshes (10), we cannot optimize for the latent code during testing. We need to provide the trained latent codes during test time.

Thank you very much! I will try it tomorrow!

**Comment by xusensun** [comment]
How to get the trained latent codes ? The code in train_i3DMM.py doesn't save the latent codes per person.

**Comment by tarun738** [comment]
Assuming the issue is closed.
